id: list_workspace_contents
learningObjectives:
  - Explore the workspace structure and understand project organization.
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "🔍 Let's start by exploring your workspace structure! This will help you understand the project layout before we dive into Go development."
          - text: "I'll run the `ls` command to show you what's in your workspace directory when you're ready."
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: run_command
        name: list_workspace
        params:
          command: "ls -la"
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: "Here's the current structure of your workspace:"
            - text: "```\n${outputs.list_workspace.data}\n```"
            - text: "Great! Now you can see the current structure of your workspace. This gives you a baseline understanding of what files and directories are available as we begin our Go development journey."
