id: 01_mcp_setup
learningObjectives:
  - Set up and configure the GitHub MCP Server in your Codespace
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Once your Codespace is ready let's add the MCP Server."
          - text: "Create `.vscode/mcp.json` file if you dont have it alrady, and add the GitHub MCP Server configuration:"
          - text: |
              ```json
              {
                "servers": {
                  "github": {
                    "type": "http",
                    "url": "https://api.githubcopilot.com/mcp/"
                  }
                }
              }
              ```
          - text: "Once you save the file, a GitHub authentication window will pop up asking you to connect with your GitHub account."
          - text: "Follow the instructions in the popup to authenticate. Once done, close the window and return to your Codespace to continue working with MCP."
          - text: ":instruction[Create the MCP configuration file] Once you've created `.vscode/mcp.json` with the GitHub MCP Server configuration, tell me and i'll validate it."
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: run_command
        name: check_mcp_url
        params:
          command: "grep -q 'https://api.githubcopilot.com/mcp/' .vscode/mcp.json && echo true || echo false"
    if:
      conditions:
        - conditionId: is_truthy
          params:
            value: "${outputs.check_mcp_url?.data}"
      then:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "✅ The MCP URL is correctly configured in your Codespace!"
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "❌ The MCP URL is missing or incorrect in your Codespace. Please update the /.vscode/mcp.json file and try again."
