id: mcp_setup
learningObjectives:
  - Set up and configure the GitHub MCP Server in your Codespace
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Once your Codespace is ready let's add the MCP Server."
          - text: "Create `.vscode/mcp.json` file if you dont have it alrady, and add the GitHub MCP Server configuration:"
          - text: |
            ```json
            {
              "servers": {
                "github": {
                  "type": "http",
                  "url": "https://api.githubcopilot.com/mcp/"
                }
              }
            }
            ```
          - text: "Once you save the file, a GitHub authentication window will pop up asking you to connect with your GitHub account."
          - text: "Follow the instructions in the popup to authenticate. Once done, close the window and return to your Codespace to continue working with MCP."
          - text: "Commit and push `.vscode/mcp.json` to complete the setup."
          - text: ":instruction[Create the MCP configuration file and commit it to your repository.] Once you've created `.vscode/mcp.json` with the GitHub MCP Server configuration and committed it, I'll detect your progress and we can move to the next step!"

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: github_pr_review
        params:
          messages:
            person: lucca
