id: 02_agent_mode_mcp_in_action
learningObjectives:
  - Use Copilot Agent to generate new feature ideas
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Time to put Agent Mode + MCP to work! 🤖"
          - text: "Now that your MCP server is configured, Copilot can talk directly to GitHub's API."
          - text: "Let's use this superpower to research and enhance your project."
          - text: ":instruction[Click the Copilot icon in top right corner to open Copilot chat next to the search bar.]"
          - text: "Lets ask Copilot to come up with new feature ideas by researching similar GitHub repositories like Kahoot, Quizizz, and Quizlet."
          - text: "`Can you find similar repositories to Kahoot, Quizizz, and Quizlet, do a quick research come up with 3 super simple new feature ideas for our quiz project? Make them short and focused.`"
          - text: "When prompted to use MCP, approve the request."
          - text: "You can ask CoPilot `Please describe the results in detail — what are its core features?`"
          - text: "Once you have the results tell me the selected feature you want to implement."
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step