id: 03_create_github_issue
learningObjectives:
  - Use Copilot to create GitHub issues for new features
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "That is an amazing idea! I'm going to document it in our issues later so we can review it together, but our Product Manager has requested a new feature."
          - text: "Let's see how GitHub Copilot reads and creates an issue for you."
          - text: "Here is a [document with the feature description](${newfeature.md}) that a Product Manager wrote for your quiz app, :instruction[upload it to your Codespace repository.]"
          - text: ":instruction[In your CoPilot chat, click the paperclip icon > Files and Folders > newfeature.md]"
          - text: "Giving context to CoPilot is important, so it can understand the task better by reading the document."
          - text: "`#codebase Can you create a GitHub issue for the new feature idea based on the attached document? Make sure you check the repository details and owner for opening the new issue.`"
          - text: "When prompted to use MCP, approve the request."
          - text: "Let me know when Copilot has successfully created the GitHub issue and send me the issue link."
trigger:
  type: user_message
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${userMessageText}"
          regex: \/issues\/\d+$
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
              - text: "Got it! Lets move on!"
        - actionId: store_user_property
          params:
            name: issueurl
            value: ${userMessageText}
        - actionId: finish_step 
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
              - text: "Thats not a GitHub issue URL is it?"
