id: 03_create_github_issue
learningObjectives:
  - Use Copilot to create GitHub issues for new features
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Great! Now let's see how a GitHub issue for the selected feature."
          - text: "Now, lets see how CoPilot can read a document and open an issue accordingly."
          - text: "Here is a document with the feature description, drag it to the CoPilot chat and ask CoPilot to create a GitHub issue based on it."
          - text: "`#codebase Can you create a GitHub issue for the new feature idea based on the attached document? Make sure you check the repository details and owner for opening the new issue.`"
          - text: "When prompted to use MCP, approve the request."
          - text: "Let me know when Copilot has successfully created the GitHub issue."
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step