id: add_database_layer
learningObjectives:
  - Integrate PostgreSQL database with proper patterns using GHCP Agent Mode.
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Time to level up with database integration! 🗄️"
          - text: "Your PostgreSQL database is already running. Now let's connect your Go API to it using GHCP Agent Mode."
          - text: "Ask GHCP Agent Mode to help you:"
          - text: "1. **Database Connection** - Set up PostgreSQL connection using lib/pq or pgx driver"
          - text: "2. **Database Models** - Create Go structs for questions, answers, and quiz results"
          - text: "3. **Migration System** - Create database tables with proper schema"
          - text: "4. **Repository Pattern** - Implement data access layer with proper separation"
          - text: "5. **Environment Configuration** - Use environment variables for database connection"
          - text: "Replace your in-memory data with actual database operations. Ensure your `/api/questions` endpoint now serves data from PostgreSQL."
          - text: ":instruction[Create a pull request with your database integration.] The PR should contain your updated code with PostgreSQL connection, database models, migrations, and repository pattern implementation. I'll automatically detect when your PR is ready for review!"

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: github_pr_review
        params:
          messages:
            person: lucca
