id: 04_solve_issues_with_agent_mode
learningObjectives:
  - Use Copilot Agent Mode to select and implement GitHub issues
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Time to put Copilot Agent Mode to work! 🧰"
          - text: "Now that you've created GitHub issue and you know which one you want to implement first, let's use Copilot to actually implement it."
          - text: "Instruct Copilot to implement a specific one:"
          - text: "`#codebase Get to work! Lets implement issue ${user.properties.issueurl}. Follow these steps: Create a new branch, Implement the feature, Push changes and open a pull request.`"
          - text: ":instruction[Once you've successfully opened a pull request for the issue implementation I'll validate it.]"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: "Great! You've successfully opened a pull request for the issue implementation. 🎉 "
      - actionId: finish_step 
