id: 04_solve_issues_with_agent_mode
learningObjectives:
  - Use Copilot Agent Mode to select and implement GitHub issues
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Time to put Copilot Agent Mode to work! 🧰"
          - text: "Now that you've created GitHub issues and you know which one you want to implement first, let's use Copilot to actually implement it."
          - text: "Ask Copilot in Chat:"
          - text: "`#codebase How many open issues are there?`"
          - text: "Then instruct Copilot to implement a specific one:"
          - text: "`#codebase lets implement issue YOURISSUEURL. Follow these steps: Create a new branch, Implement the fix or feature, Push changes and open a pull request.`"
          - text: ":instruction[Tell me when you've successfully opened a pull request for the issue implementation.]"
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step