id: 05_validate_and_merge_ai_code
learningObjectives:
  - Responsibly review and validate AI-generated code
  - Practice safe merging of AI-generated pull requests
  - Close GitHub issues with proper communication
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Time to close up your issue and see how CoPilot adds context after! ✅"
          - text: "This is a crucial step in responsible AI-assisted development."
          - text: "Here's what you need to do:"
          - text: "After merging, ask Copilot in Chat:"
          - text: "`Add a closing comment to the issue we just finished. Provide a 1-sentence summary of the fix and thank the commenters.`"
          - text: ":instruction[Tell me when you've successfully merged the PR and closed the issue.]"
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step